apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm2-web
  namespace: racobniasse-dev
  labels:
    role: webserver
    zone: dmz
spec:
  runStrategy: Always
  instancetype:
    kind: VirtualMachineClusterInstancetype
    name: u1.micro
  template:
    metadata:
      labels:
        role: webserver
        zone: dmz
    spec:
      domain:
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/containerdisks/fedora:latest
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: fedora
            password: fedora123
            chpasswd: {expire: False}
            packages:
              - nginx
              - nodejs
              - npm
